language: node_js
script: npm start
node_js:
  - "v10.0.0"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b0a361d8fd9c40ea2bb2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
